curl -o jquery.min.js -k https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js
curl -o react.production.min.js -k https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js
curl -o react-dom.production.min.js -k https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.2.0/umd/react-dom.production.min.js
curl -o babel.min.js -k https://unpkg.com/@babel/standalone@7.22.6/babel.min.js
curl -o babel.min.js.map -k https://unpkg.com/@babel/standalone@7.22.6/babel.min.js.map
curl -o moment.js -k https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js
curl -o dayjs.min.js -k https://cdnjs.cloudflare.com/ajax/libs/dayjs/1.11.9/dayjs.min.js
curl -o antd.min.js -k https://cdnjs.cloudflare.com/ajax/libs/antd/5.6.4/antd.min.js
curl -o antd.min.js.map -k https://cdnjs.cloudflare.com/ajax/libs/antd/5.6.4/antd.min.js.map
curl -o reset.min.css -k https://cdnjs.cloudflare.com/ajax/libs/antd/5.6.4/reset.min.css
